import numpy as np
from typing import List
from segment import Segment
import itertools
"""
    This class create a partition of the space into rectangles, and creates the segments.
    Currently the rectangles are of equal size.
    ...
    
    Attributes
    ----------
    segments : List[Segment]
        The segments generated by the class.
    
    Methods
    -------
    segments(self):
    Returns the segments held in the class.
    
    generate_segments(d: int, b_low: List, b_high: List) -> List[Segment]
        The method partitions the space into rectangles and create a Segment object for each rectangle.
    
"""

class SegmentsGenerator:
    def __init__(self, d: int, b_low: List, b_high: List):
        self._segments = self.generate_segments(d, b_low, b_high)

    @property
    def segments(self):
        return self._segments

    @staticmethod
    def generate_segments(d: int, b_low: List, b_high: List) -> List[Segment]:
        x_low = [np.arange(b_low[i], b_high[i] - 1, 1) for i in range(d)]
        x_high = [np.arange(b_low[i] + 1, b_high[i], 1) for i in range(d)]
        low_edges = [low_edge for low_edge in itertools.product(*x_low)]
        high_edges = [high_edge for high_edge in itertools.product(*x_high)]
        return [Segment(d, low_edges[i], high_edges[i]) for i in range(len(low_edges))]
